platform :ios, '13.0'

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      
      # Enable NFC capabilities
      config.build_settings['OTHER_SWIFT_FLAGS'] = '$(inherited) -D ENABLE_NFC'
    end
  end
end